#If it is not a bot write human else Bot
#Horse
print("In fields of freedom, there stands a horse,")
print("Majestic and strong, of untamed force,")
print("With eyes that blaze with a fiery light,")
print("A creature of grace, a wondrous sight.")
print("Its every stride is a dance of passion,")
print("A wild spirit that knows no ration,")
print("In the thundering hooves that fiercely pound,")
print("The earth itself feels the tremors around.")
print("With mane that flows like a river's stream,")
print("It gallops through meadows, fulfilling its dream,")
print("A symbol of strength and untamed grace,")
print("In its presence, the world finds its place.")
print("In partnership with a rider's heart,")
print("It carries dreams to every part,")
print("A bond of trust, forged deep and true,")
print("In the world of horses, passions renew.")
print("So, let us learn from this noble steed,")
print("To follow our hearts, to fulfill the need,")
print("To live with purpose, and never be swayed,")
print("In the horse's passion, let our dreams be made.")
Question = input ("Bot or not?")
if Question == ("Bot"):
	print("well done!")
elif Question == ("Human"):
	print("try again.")
